<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>Lodeworks</AssemblyName>
    <Version>0.1.0</Version>
    <KSPBT_ModRoot>$(MSBuildThisFileDirectory)..\artifacts\GameData\Lodeworks\</KSPBT_ModRoot>
    <KSPBT_ModPluginFolder>Plugins</KSPBT_ModPluginFolder>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="KSPBuildTools" Version="1.0.0" PrivateAssets="all" />
    <ProjectReference Include="..\Lodeworks.Sim\Lodeworks.Sim.csproj" />
  </ItemGroup>
  <Target Name="CopySimulationAssembly" AfterTargets="Build">
    <MakeDir Directories="$(KSPBT_ModRoot)$(KSPBT_ModPluginFolder)" />
    <Copy SourceFiles="$(MSBuildThisFileDirectory)..\Lodeworks.Sim\bin\$(Configuration)\net48\Lodeworks.Sim.dll" DestinationFolder="$(KSPBT_ModRoot)$(KSPBT_ModPluginFolder)" />
  </Target>
</Project>

